-- Tables for players' characters

Albert = Character{
    name = "An Gai Shan (Gekido)",
    bod = 7,
    agi = 4,
    rea = 6,
    str = 8,
    cha = 1,
    int = 3,
    log = 2,
    wil = 3,
    edg = 5,
    ess = 6,
    mag = 7,
    skills = {
        -- Combat Active Skills
        unarmed =   { rating = 5, att = "agi", mod = 4 },
        archery =   { rating = 0, att = "agi", mod = 0 },
        auto =      { rating = 0, att = "agi", mod = 0 },
        blades =    { rating = 0, att = "agi", mod = 0 },
        clubs =     { rating = 0, att = "agi", mod = 0 },
        heavy =     { rating = 0, att = "agi", mod = 0 },
        longarms =  { rating = 0, att = "agi", mod = 0 },
        pistols =   { rating = 0, att = "agi", mod = 0 },
        thrown =    { rating = 0, att = "agi", mod = 0 },
        -- Physical Active Skills
        gymnastics =    { rating = 5, att = "agi", mod = 0 },
        running =       { rating = 5, att = "str", mod = 0 },
        perception =    { rating = 3, att = "int", mod = 0 },
        swimming =      { rating = 2, att = "str", mod = 0 },
        tracking =      { rating = 2, att = "int", mod = 0 },
        disguise =      { rating = 0, att = "int", mod = 0 },
        diving =        { rating = 0, att = "bod", mod = 0 },
        escape =        { rating = 0, att = "agi", mod = 0 },
        freefall =      { rating = 0, att = "bod", mod = 0 },
        sneaking =      { rating = 0, att = "agi", mod = 0 },
        survival =      { rating = 0, att = "wil", mod = 0 },
        -- Social Active Skills
        con =           { rating = 0, att = "cha", mod = 0 },
        negotiation =   { rating = 0, att = "cha", mod = 0 },
        impersonation = { rating = 0, att = "cha", mod = 0 },
        etiquette =     { rating = 0, att = "cha", mod = 0 },
        intimidation =  { rating = 0, att = "cha", mod = 0 },
        leadership =    { rating = 0, att = "cha", mod = 0 },
        instruction =   { rating = 0, att = "cha", mod = 0 },
        performance =   { rating = 0, att = "cha", mod = 0 },
        -- Technical Active Skills
        navigation =    { rating = 2, att = "int", mod = 0 },
        armorer =       { rating = 0, att = "log", mod = 0 },
        computer =      { rating = 0, att = "log", mod = 0 },
        cybercombat =   { rating = 0, att = "log", mod = 0 },
        demolitions =   { rating = 0, att = "log", mod = 0 },
        firstaid =      { rating = 0, att = "log", mod = 0 },
        forgery =       { rating = 0, att = "log", mod = 0 },
        hacking =       { rating = 0, att = "log", mod = 0 },
        -- Vehicle Active Skills
        pilot_ground =  { rating = 2, att = "rea", mod = 0 },
        gunnery =       { rating = 0, att = "agi", mod = 0 },
        pilot_water =   { rating = 0, att = "rea", mod = 0 },
        -- Knowledge Skills
        area_seattle =  { rating = 3, att = "int", mod = 0 },
        kungfu =        { rating = 4, att = "int", mod = 0 },
        philosophy =    { rating = 3, att = "log", mod = 0 },
    },
    weapon = {
        unarmed = { skill = "unarmed", acc = 11, dmg = 11, ap = 0, reach = 1 },
    },
    armor_rating = 12,
    init_dice = 3,
};

Tommy = Character{
    name = "Randy Magnum (Sterling)",
    bod = 2,
    agi = 5,
    rea = 2,
    str = 2,
    cha = 9,
    int = 2,
    log = 2,
    wil = 2,
    edg = 5,
    ess = 6,
    mag = 6,
    skills = {
        -- Combat Active Skills
        unarmed =   { rating = 3, att = "agi", mod = 0 },
        archery =   { rating = 0, att = "agi", mod = 0 },
        auto =      { rating = 0, att = "agi", mod = 0 },
        blades =    { rating = 3, att = "agi", mod = 0 },
        clubs =     { rating = 3, att = "agi", mod = 0 },
        heavy =     { rating = 0, att = "agi", mod = 0 },
        longarms =  { rating = 0, att = "agi", mod = 0 },
        pistols =   { rating = 5, att = "agi", mod = 5 },
        thrown =    { rating = 0, att = "agi", mod = 0 },
        -- Physical Active Skills
        gymnastics =    { rating = 5, att = "agi", mod = 0 },
        running =       { rating = 5, att = "str", mod = 0 },
        perception =    { rating = 3, att = "int", mod = 0 },
        swimming =      { rating = 5, att = "str", mod = 0 },
        tracking =      { rating = 1, att = "int", mod = 0 },
        disguise =      { rating = 5, att = "int", mod = 3 },
        diving =        { rating = 0, att = "bod", mod = 0 },
        escape =        { rating = 2, att = "agi", mod = 0 },
        freefall =      { rating = 1, att = "bod", mod = 0 },
        sneaking =      { rating = 6, att = "agi", mod = 0 },
        survival =      { rating = 1, att = "wil", mod = 0 },
        -- Social Active Skills
        con =           { rating = 3, att = "cha", mod = 2 },
        negotiation =   { rating = 3, att = "cha", mod = 0 },
        impersonation = { rating = 2, att = "cha", mod = 0 },
        etiquette =     { rating = 1, att = "cha", mod = 0 },
        intimidation =  { rating = 1, att = "cha", mod = 0 },
        leadership =    { rating = 1, att = "cha", mod = 0 },
        instruction =   { rating = 0, att = "cha", mod = 0 },
        performance =   { rating = 0, att = "cha", mod = 0 },
        -- Technical Active Skills
        navigation =    { rating = 1, att = "int", mod = 0 },
        armorer =       { rating = 0, att = "log", mod = 0 },
        computer =      { rating = 0, att = "log", mod = 0 },
        cybercombat =   { rating = 0, att = "log", mod = 0 },
        demolitions =   { rating = 0, att = "log", mod = 0 },
        firstaid =      { rating = 0, att = "log", mod = 0 },
        forgery =       { rating = 6, att = "log", mod = 0 },
        hacking =       { rating = 0, att = "log", mod = 0 },
        locksmith =     { rating = 4, att = "agi", mod = 0 },
        -- Vehicle Active Skills
        pilot_ground =  { rating = 2, att = "rea", mod = 0 },
        gunnery =       { rating = 0, att = "agi", mod = 0 },
        pilot_water =   { rating = 0, att = "rea", mod = 0 },
        -- Knowledge Skills
        area_seattle =  { rating = 1, att = "int", mod = 0 },
        art =           { rating = 2, att = "log", mod = 0 },
        fashion =       { rating = 2, att = "int", mod = 0 },
        literature =    { rating = 3, att = "log", mod = 0 },
    },
    weapon = {
        unarmed = { skill = "unarmed", acc = 3, dmg = 2, ap = 0, reach = 0 }, -- Stun
        taurus_omni6 =   { skill = "pistols", acc = 7, dmg = 6, ap = 0, rc = 1 },
    },
    armor_rating = 14,
    init_dice = 1,
};

Alex = Character{
    name = "Wilco Roger (Over)",
    bod = 6,
    agi = 5,
    rea = 4,
    str = 6,
    cha = 2,
    int = 5,
    log = 3,
    wil = 5,
    edg = 2,
    ess = 4.31,
    mag = 0,
    skills = {
        -- Combat Active Skills
        unarmed =   { rating = 0, att = "agi", mod = 0 },
        archery =   { rating = 0, att = "agi", mod = 0 },
        auto =      { rating = 0, att = "agi", mod = 0 },
        blades =    { rating = 6, att = "agi", mod = 0, spec = "swords" },
        clubs =     { rating = 0, att = "agi", mod = 0 },
        heavy =     { rating = 0, att = "agi", mod = 0 },
        longarms =  { rating = 0, att = "agi", mod = 0 },
        pistols =   { rating = 5, att = "agi", mod = 0, spec = "semiauto" },
        thrown =    { rating = 0, att = "agi", mod = 0 },
        -- Physical Active Skills
        gymnastics =    { rating = 0, att = "agi", mod = 0 },
        running =       { rating = 1, att = "str", mod = 0, spec = "urban" },
        perception =    { rating = 1, att = "int", mod = 0, spec = "search" },
        swimming =      { rating = 0, att = "str", mod = 0 },
        disguise =      { rating = 0, att = "int", mod = 0 },
        diving =        { rating = 0, att = "bod", mod = 0 },
        escape =        { rating = 0, att = "agi", mod = 2 },
        freefall =      { rating = 0, att = "bod", mod = 0 },
        sneaking =      { rating = 0, att = "agi", mod = 2 },
        survival =      { rating = 2, att = "wil", mod = 0, spec = "urban" },
        animals =       { rating = 0, att = "cha", mod = 0 },
        tracking =      { rating = 0, att = "int", mod = 0 },
        -- Social Active Skills
        con =           { rating = 0, att = "cha", mod = 0 },
        negotiation =   { rating = 0, att = "cha", mod = 0 },
        impersonation = { rating = 0, att = "cha", mod = 0 },
        etiquette =     { rating = 0, att = "cha", mod = 0 },
        intimidation =  { rating = 0, att = "cha", mod = 0 },
        leadership =    { rating = 0, att = "cha", mod = 0 },
        instruction =   { rating = 0, att = "cha", mod = 0 },
        performance =   { rating = 0, att = "cha", mod = 0 },
        -- Technical Active Skills
        navigation =    { rating = 0, att = "int", mod = 0 },
        armorer =       { rating = 0, att = "log", mod = 0 },
        computer =      { rating = 0, att = "log", mod = 0 },
        cybercombat =   { rating = 0, att = "log", mod = 0 },
        demolitions =   { rating = 0, att = "log", mod = 0 },
        firstaid =      { rating = 0, att = "log", mod = 0 },
        forgery =       { rating = 0, att = "log", mod = 0 },
        hacking =       { rating = 0, att = "log", mod = 0 },
        -- Vehicle Active Skills
        pilot_ground =  { rating = 1, att = "rea", mod = 0, spec = "wheeled" },
        gunnery =       { rating = 0, att = "agi", mod = 0 },
        pilot_water =   { rating = 0, att = "rea", mod = 0 },
        -- Knowledge Skills
        lang_japan =    { rating = 1, att = "int", mod = 0, spec = "speak" },
        art =           { rating = 2, att = "log", mod = 0, spec = "asia-pacific" },
        combat_tactics ={ rating = 4, att = "int", mod = 0, spec = "urban" },
        history =       { rating = 2, att = "log", mod = 0, spec = "asia-pacific" },
        literature =    { rating = 2, att = "int", mod = 0, spec = "asia-pacific" },
    },
    weapon = {
        unarmed = { skill = "unarmed", acc = 8, dmg = 6, ap = 0, reach = 0 }, -- Stun
        katana =  { skill = "blades", acc = 7, dmg = 9, ap = 3, reach = 1 },
        ares_crusader_2 = { skill = "pistols", acc = 7, dmg = 7, ap = 0, mode = "sa/bf", rc = 4 },
        ares_predator_5 = { skill = "pistols", acc = 7, dmg = 8, ap = 1, mode = "sa", rc = 2 },
    },
    armor_rating = 9,
    init_dice = 1,
};

George = Character{
    name = "Ximo Lopez Fonseca Guadarrama Valderrama (Pele)",
    bod = 5,
    agi = 6,
    rea = 6,
    str = 3,
    cha = 2,
    int = 4,
    log = 2,
    wil = 2,
    edg = 5,
    ess = 5.15,
    mag = 0,
    skills = {
        -- Combat Active Skills
        unarmed =   { rating = 0, att = "agi", mod = 0 },
        archery =   { rating = 0, att = "agi", mod = 0 },
        auto =      { rating = 4, att = "agi", mod = 0 },
        blades =    { rating = 0, att = "agi", mod = 0 },
        clubs =     { rating = 0, att = "agi", mod = 0 },
        heavy =     { rating = 0, att = "agi", mod = 0 },
        longarms =  { rating = 0, att = "agi", mod = 0 },
        pistols =   { rating = 4, att = "agi", mod = 0 },
        thrown =    { rating = 0, att = "agi", mod = 0 },
        -- Physical Active Skills
        gymnastics =    { rating = 1, att = "agi", mod = 0 },
        running =       { rating = 1, att = "str", mod = 0 },
        perception =    { rating = 0, att = "int", mod = 0 },
        swimming =      { rating = 1, att = "str", mod = 0 },
        tracking =      { rating = 0, att = "int", mod = 0 },
        disguise =      { rating = 0, att = "int", mod = 0 },
        diving =        { rating = 0, att = "bod", mod = 0 },
        escape =        { rating = 2, att = "agi", mod = 0 },
        freefall =      { rating = 0, att = "bod", mod = 0 },
        sneaking =      { rating = 0, att = "agi", mod = 0 },
        survival =      { rating = 0, att = "wil", mod = 0 },
        -- Social Active Skills
        con =           { rating = 0, att = "cha", mod = 0 },
        negotiation =   { rating = 0, att = "cha", mod = 0 },
        impersonation = { rating = 0, att = "cha", mod = 0 },
        etiquette =     { rating = 2, att = "cha", mod = 0 },
        intimidation =  { rating = 0, att = "cha", mod = 0 },
        leadership =    { rating = 0, att = "cha", mod = 0 },
        instruction =   { rating = 0, att = "cha", mod = 0 },
        performance =   { rating = 0, att = "cha", mod = 0 },
        -- Technical Active Skills
        navigation =    { rating = 2, att = "int", mod = 0 },
        armorer =       { rating = 0, att = "log", mod = 0 },
        computer =      { rating = 0, att = "log", mod = 0 },
        cybercombat =   { rating = 0, att = "log", mod = 0 },
        demolitions =   { rating = 0, att = "log", mod = 0 },
        firstaid =      { rating = 0, att = "log", mod = 0 },
        forgery =       { rating = 0, att = "log", mod = 0 },
        hacking =       { rating = 0, att = "log", mod = 0 },
        aero_mechanic = { rating = 1, att = "log", mod = 0 },
        auto_mechanic = { rating = 1, att = "log", mod = 0 },
        indu_mechanic = { rating = 1, att = "log", mod = 0 },
        naut_mechanic = { rating = 1, att = "log", mod = 0 },
        -- Vehicle Active Skills
        pilot_ground =  { rating = 4, att = "rea", mod = 0 },
        gunnery =       { rating = 5, att = "agi", mod = 0 },
        pilot_water =   { rating = 1, att = "rea", mod = 0 },
        pilot_air =     { rating = 4, att = "rea", mod = 0 },
        -- Knowledge Skills
        area_seattle =  { rating = 2, att = "int", mod = 0 },
        business =      { rating = 2, att = "log", mod = 0 },
        firearms =      { rating = 4, att = "log", mod = 0 },
        underworld =    { rating = 4, att = "int", mod = 0 },
    },
    weapon = {
        unarmed =   { skill = "unarmed", acc = 6, dmg = 3, ap = 0, reach = 0 }, -- Stun
        mgl12 =     { skill = "thrown", acc = 6, dmg = 0, ap = 0, rc = 1 },
        as7 =       { skill = "longarms", acc = 6, dmg = 13, ap = 1, mode = "sa/bf", rc = 3 },
        security600 = { skill = "pistols", acc = 8, dmg = 7, ap = 0, mode = "sa", rc = 3 },
        fnhar =     { skill = "auto", acc = 7, dmg = 10, ap = 2, mode = "sa/bf/fa", rc = 3 },
        thermal_g = { skill = "thrown", acc = 6, dmg = 0, ap = 0, rc = 1 },
        hk227 =     { skill = "auto", acc = 7, dmg = 7, ap = 0, mode = "sa/bf/fa", rc = 2 },
        mini_g =    { skill = "thrown", acc = 0, dmg = 16, ap = 2, rc = 1 },
        ruger_shawk={ skill = "pistols", acc = 7, dmg = 9, ap = 2, mode = "ss", rc = 4 },
    },
    armor_rating = 12,
    init_dice = 1,
};

Jason = Character{
    name = "Longshot Darkhawk",
    bod = 5,
    agi = 6,
    rea = 5,
    str = 4,
    cha = 3,
    int = 3,
    log = 3,
    wil = 3,
    edg = 4,
    ess = 5.1,
    mag = 0,
    skills = {
        -- Combat Active Skills
        unarmed =   { rating = 1, att = "agi", mod = 0 },
        archery =   { rating = 0, att = "agi", mod = 0 },
        auto =      { rating = 6, att = "agi", mod = 0 },
        blades =    { rating = 0, att = "agi", mod = 0 },
        clubs =     { rating = 0, att = "agi", mod = 0 },
        heavy =     { rating = 1, att = "agi", mod = 0 },
        longarms =  { rating = 6, att = "agi", mod = 0 },
        pistols =   { rating = 6, att = "agi", mod = 0 },
        thrown =    { rating = 0, att = "agi", mod = 0 },
        exotic_melee={rating = 6, att = "agi", mod = 0 },
        -- Physical Active Skills
        gymnastics =    { rating = 4, att = "agi", mod = 2 },
        running =       { rating = 4, att = "str", mod = 2 },
        perception =    { rating = 6, att = "int", mod = 0 },
        swimming =      { rating = 4, att = "str", mod = 0 },
        tracking =      { rating = 3, att = "int", mod = 0 },
        disguise =      { rating = 0, att = "int", mod = 0 },
        diving =        { rating = 0, att = "bod", mod = 0 },
        escape =        { rating = 2, att = "agi", mod = 0 },
        freefall =      { rating = 2, att = "bod", mod = 0 },
        sneaking =      { rating = 6, att = "agi", mod = 2 },
        survival =      { rating = 3, att = "wil", mod = 0 },
        -- Social Active Skills
        con =           { rating = 0, att = "cha", mod = 0 },
        negotiation =   { rating = 1, att = "cha", mod = 0 },
        impersonation = { rating = 2, att = "cha", mod = 0 },
        etiquette =     { rating = 0, att = "cha", mod = 0 },
        intimidation =  { rating = 0, att = "cha", mod = 0 },
        leadership =    { rating = 0, att = "cha", mod = 0 },
        instruction =   { rating = 0, att = "cha", mod = 0 },
        performance =   { rating = 0, att = "cha", mod = 0 },
        -- Technical Active Skills
        navigation =    { rating = 3, att = "int", mod = 0 },
        armorer =       { rating = 2, att = "log", mod = 0 },
        computer =      { rating = 0, att = "log", mod = 0 },
        cybercombat =   { rating = 0, att = "log", mod = 0 },
        demolitions =   { rating = 0, att = "log", mod = 0 },
        firstaid =      { rating = 3, att = "log", mod = 0 },
        forgery =       { rating = 0, att = "log", mod = 0 },
        hacking =       { rating = 0, att = "log", mod = 0 },
        locksmith =     { rating = 3, att = "agi", mod = 0 },
        palming =       { rating = 2, att = "agi", mod = 0 },
        -- Vehicle Active Skills
        pilot_ground =  { rating = 0, att = "rea", mod = 0 },
        gunnery =       { rating = 0, att = "agi", mod = 0 },
        pilot_water =   { rating = 0, att = "rea", mod = 0 },
        -- Knowledge Skills
        lang_sperethiel =  { rating = 3, att = "int", mod = 0 },
        building_layouts = { rating = 2, att = "log", mod = 0 },
        gun_design =    { rating = 3, att = "log", mod = 0, spec = "sniper" },
        infil_tech =    { rating = 2, att = "log", mod = 0 },
        psychology =    { rating = 1, att = "log", mod = 0 },

    },
    weapon = {
        unarmed = { skill = "unarmed", acc = 6, dmg = 4, ap = 0, reach = 0 }, -- Stun
        mono_whip = { skill = "exotic_melee", acc = 5, dmg = 12, ap = 8, reach = 2 },
        ares_alpha = { skill = "auto", acc = 7, dmg = 11, ap = 2, rc = 2, mode = "sa/bf/fa", },
        ares_glaunch = { skill = "auto", acc = 6, dmg = 0, ap = 0, rc = 2, },
        ares_light_fire = { skill = "pistols", acc = 8, dmg = 6, ap = 0, rc = 2, },
        mini_frag = { skill = "thrown", acc = 0, dmg = 0, ap = -5, rc = 2 },
        ruger_101 = { skill = "longarms", acc = 8, dmg = 11, ap = 3, rc = 12 },
    },
    armor_rating = 9,
    init_dice = 1,
};

players = {
  Albert,
  Tommy,
  Alex,
  George,
  Jason,
};
